### ISSUE TITLE
Calling assertjGen tasks deletes all initialy existing files.

### ISSUE THREAD

**Issue by petromir** [opengl-8080/assertjGen-gradle-plugin#1]
I have the following gradle configuration for `assertjGen`

``` gradle
assertjGen {
    classOrPackageNames = ['com.example.Person']
    outputDir = 'src/java/test/'
    assertjGenerator = 'org.assertj:assertj-assertions-generator:2.0.0'
}
```

Running `gradle assertjGen` deletes all initially existing files/directories under `src/java/test/` folder. 

Can the plugin deletes only the class or the packages in the output directory specified by`classOrPackageNames` property, so the existing tests will be kept in place?

**Comment by opengl-8080** [comment]
I think that generated files(made by assertjGen task) should be separated from handmade files(in `src/java/test`).
Because it is easy to understand which files are auto generated or not.

Please set `outputDir` different from `src/java/test`.
For example `src/java/test-gen`.
Do you have any reasons that you must set `src/java/test`?

If you use IDE (IntelliJ or Eclipse), you need modify `build.gradle` like following.

**IntelliJ**

``` groovy
apply plugin: 'idea'

idea {
  module {
    testSourceDirs += file('src/java/test-gen')
  }
}
```

Please refresh all Gradle projects on IntelliJ.

**Eclipse**

``` groovy
apply plugin: 'eclipse'

eclipse {
    classpath {
        file {
            withXml {
                def node = it.asNode()
                node.appendNode(
                    'classpathentry',
                    [kind: 'src', path: 'src/java/test-gen']
                )
            }
        }
    }
}
```

Please execute `gradle cleanEclipse eclipse` command.

**Comment by petromir** [comment]
I would like to prevent creation of another source set for such kind of operations. Imagine that I also have few others that do similar code generations.
I will be glad to see an option or another way to prevent deletion of existing files. Thanks

**Comment by opengl-8080** [comment]
Is my understanding of your thinking correct?
- If you use multiple code generator tools, you will need set source set for each tools.
- It is so hassle.
- So you want to generate files into `src/java/test`. Then you want to delete only generated files.

I thought this problem.

I think that deleting packages of `classOrPackageNames` is not good.
Because, packages may have non generated files.

```
|-src/main/java/
|  `-foo/
|      `-Foo.java
`-src/test/java
   `-foo/
       |-FooTest.java    : must not delete!
       `-FooAssert.java  : must delete!
```

My suggestion is adding `cleanOnlyFiles` and `cleanFilesPattern` options.

`cleanOnlyFiles` is boolean option.
If this option is true, assertjClean task only deletes matched files by `cleanFilesPattern` under the `outputDir`.
Default is false.

`cleanFilesPattern` is String option.
To set reguler expression.
If `cleanOnlyFiles` is true, matched files by this pattern under the `outputDir` will be deleted at assertjClean.
Default is `/^.*Assert\.java$/`.

So you will modify `build.gradle` like following.

``` diff
assertjGen {
    classOrPackageNames = ['com.example.Person']
    outputDir = 'src/java/test/'
    assertjGenerator = 'org.assertj:assertj-assertions-generator:2.0.0'
+   cleanOnlyFiles = true
}
```

How about this for an idea?

**Comment by petromir** [comment]
Great idea!
If `cleanOnlyFiles` and `cleanFilesPattern` must be used together why the latter is not included in the example above?
Thanks for your efforts.

**Comment by opengl-8080** [comment]
`cleanFilesPattern` has default value (`/^.*Assert\.java$/`).
So you can ommit it.

If you want select delete files, you set this option.
(It might be rare...)

**Comment by petromir** [comment]
Sorry, my mistake. Thanks you!
