### ISSUE TITLE
Is there a possibility of generating asserts from build/classes/kotlin ?

### ISSUE THREAD

**Issue by MikeShysh** [opengl-8080/assertjGen-gradle-plugin#17]
Hi,

kotlin plugin for gradle 1.1.51.

Previously, asserts were successfully generated from *.kt files from build/classes/java. 
Starting from kotlin plugin for gradle 1.1.51, task `:copyMainKotlinClasses` was removed from the lifecycle. As a result, build/classes/java is empty. 
Is it possible to specify somehow directory `build/classes/kotlin` for assertjGen plugin? I tried to play with `sourceSets` but without success. Please advise.

**Comment by opengl-8080** [comment]
Thank you your bug report.

In Gradle 4.x, this problem is occured.
Gradle 4.x separates output directories for each JVM languages.
> [Gradle 4.0 Warning: What is this - Help/Discuss - Gradle Forums](https://discuss.gradle.org/t/gradle-4-0-warning-what-is-this/23004/2)

`getClassDirs()` method was added to `SourceSetOutput` instead of `getClassDir()`.
`getClassDir()` was become to deprecated.

However, this plugin uses `getClassDir()` still.
`getClassDir()` returns `build/classes/java/main` only (no `build/classes/kotlin/main`).

I try fix this problem.

**Comment by opengl-8080** [comment]
Thank you for your report.

I guess that updating the Gradle causes this problem.

I tried `assertjGen` in kotlin-plugin 1.1.51 and Gradle 3.x, but this problem was not occured.
However in Gradle 4.x, this problem was occured even though using kotlin-plugin 1.1.50.


Gradle 4.x separates output directories for each JVM languages.
> [Gradle 4.0 Warning: What is this - Help/Discuss - Gradle Forums](https://discuss.gradle.org/t/gradle-4-0-warning-what-is-this/23004/2)

`getClassDirs()` method was added to `SourceSetOutput` instead of `getClassDir()`.
`getClassDir()` was become to deprecated.

However, this plugin uses `getClassDir()` still.
`getClassDir()` returns `build/classes/java/main` only (no `build/classes/kotlin/main`).

I try fix this problem.

**Comment by MikeShysh** [comment]
Hi,

> I guess that updating the Gradle causes this problem.

Yes, the issue is in Gradle version as well. I have 4.2

> I try fix this problem.

Thanks, it would be great. 
As a workaround, I added a custom gradle task which copies `/build/classes/kotlin/*` into  `build/classes/java/`

**Comment by opengl-8080** [comment]
I bult draft version.

[assertjGen-gradle-plugin-1.1.8-draft.zip](https://github.com/opengl-8080/assertjGen-gradle-plugin/files/1352342/assertjGen-gradle-plugin-1.1.8-draft.zip)

Would you please test it?

**build.gradle**

```groovy
buildscript {
    dependencies {
        classpath files("path/to/assertjGen-gradle-plugin-1.1.8-draft.jar")
    }
}

apply plugin: "com.github.opengl-BOBO.assertjGen"

```

**Comment by MikeShysh** [comment]
Hi,

I've checked. It works as expected. Asserts were generated and warning is not observed anymore.
Waiting for new release in the repo=)
Thanks
